export const login = state => state.auth.login
export const token = state => state.auth.token
export const userInfo = state => state.userInfo.userInfo
export const home_timeline = state => state.home_timeline.statuses
export const public_timeline = state => state.public_timeline.statuses
export const my_content = state => state.my_content.statuses
export const home_timeline_refresh = state => state.home_timeline.refresh
export const public_timeline_refresh = state => state.public_timeline.refresh
export const my_content_refresh = state => state.my_content.refresh
export const image_zoom_url = state => state.image_zoom.image_url
export const image_zoom_show = state => state.image_zoom.show
export const detail_content = state => state.detail_content.content
export const comments = state => state.content_comments.comments
export const comments_refresh = state => state.content_comments.refresh
export const at_me_status = state => state.at_me_status.statuses
export const at_me_status_refresh = state => state.at_me_status.refresh
export const at_me_comment = state => state.at_me_comment.comments
export const at_me_comment_refresh = state => state.at_me_comment.refresh
export const receive_comment = state => state.receive_comment.comments
export const receive_comment_refresh = state => state.receive_comment.refresh
export const send_comment = state => state.send_comment.comments
export const send_comment_refresh = state => state.send_comment.refresh
export const my_follower = state => state.my_follower.users
export const my_follower_refresh = state => state.my_follower.refresh
export const my_friend = state => state.my_friend.users
export const my_friend_refresh = state => state.my_friend.refresh
