export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const TOKEN = 'token'
export const USERINFO = 'userInfo'
export const HOME_TIMELINE = 'home_timeline'
export const HOME_TIMELINE_REFRESH = 'home_timeline_refresh'
export const IMAGE_ZOOM = 'image_zoom'
